---
    - name: Install prerequisites
      dnf:
        name:
          - java-1.8.0-openjdk
          - epel-release
          - wget
          - which
        state: latest
        use_backend: dnf4

    - name: Add Elasticsearch RPM repository
      shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add Elasticsearch YUM repository
      copy:
        content: |
          [elasticsearch-7.x]
          name=Elasticsearch repository for 7.x packages
          baseurl=https://artifacts.elastic.co/packages/7.x/yum
          gpgcheck=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled=1
          autorefresh=1
          type=rpm-md
        dest: /etc/yum.repos.d/elasticsearch.repo
      become: yes

    - name: Install Elasticsearch
      dnf:
        name: elasticsearch
        use_backend: dnf4
        state: latest

    - name: Install Kibana
      dnf:
        name: kibana
        use_backend: dnf4
        state: latest

    - name: Install Logstash for CentOS
      dnf:
        name: logstash
        use_backend: dnf4
        state: latest
